# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[prod.deploy.parameters]
stack_name = "url-shortenernpl-prod"
resolve_s3 = true
s3_prefix = "url-shortenernpl-prod"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvName=\"prod\" UrlTableName=\"UrlTable-prod\" UsersTableName=\"UsersTable-prod\" ApiName=\"UrlShortenerApi-prod\" StageName=\"prod\" OriginalUrlIndexName=\"OriginalUrlIndex\""
image_repositories = []

[prod.global.parameters]
region = "ap-south-1"

[dev.deploy.parameters]
stack_name = "url-shortenernpl-dev"
resolve_s3 = true
s3_prefix = "url-shortenernpl-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvName=\"dev\" UrlTableName=\"UrlTable-dev\" UsersTableName=\"UsersTable-dev\" ApiName=\"UrlShortenerApi-dev\" StageName=\"dev\" OriginalUrlIndexName=\"OriginalUrlIndex\""
image_repositories = []

[dev.global.parameters]
region = "ap-south-1"
